language: python
env:
  global:
    - "FTP_USER=zhangbin"
    - "FTP_PASSWORD=zhangbin123"
python:
    - 2.7

install: 
    - python setup.py install
    - pip install coveralls
script: 
    trial cotools
after_success:
    - coveralls
    - "find ./testci -type f -exec curl --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD  -T {} ftp://120.27.108.133/{}"
